### ISSUE TITLE
Fix items edition

### ISSUE THREAD

**Issue by alexisLefebvre** [FriendsOfVictoire/WidgetSliderBundle#34]
- [x] We can't remove an element once it has been added
- [x] Items are not visually separated
- [x] Items can't be collapsed (code removed in https://github.com/FriendsOfVictoire/WidgetSliderBundle/commit/6a6429ed4c7c933e19dba2ca2d5f76dd6114e4b3#diff-2dd33ee283b6765d73f86c842a668ac4L76 )
- [x] Some fields are deprecated → Fields should not be deprecated anymore

**Comment by alexislefebvre** [comment]
Fields should not be deprecated anymore.
